### ISSUE TITLE
Smart Cranker clientside tool

### ISSUE THREAD

**Issue by skynetcap** [openbook-dex/resources#20]
**Background:** Currently crankers run a crank tool that manually is fed a list of marketIds. We want a dynamic version, with more intelligence.

This new project would be "smart" by:
- dynamically getting all markets from the chain (or via an OS api). 
- maximum instructions per TX
- perfectly crafted list OOAs in queue
- Multiple markets per TX
- Lower priority markets in less frequent batches.

This would be a client-side tool that anyone could run, that would only need 1 or 2 person running to power all of open book. This could function instead of on-chain incentives for now. Additionally there has been spam-related concerns w/ on-chain incentives. Thus this could be a much safer approach. Tip jars can fund this for each community-verified cranker.

**Comment by skynetcap** [comment]
I have bandwidth start this closer to start of February.

**Comment by solserer-labs** [comment]
This would a very welcome addition.

**Comment by zahin-mohammad** [comment]
👀 anyone have a bounty for this?

**Comment by skynetcap** [comment]
Merging efforts with https://github.com/SpaceMonkeyForever/openbook-cranker
